/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import clases.Alumno;
import clases.CLogin;
import clases.Admin;
import clases.Conexion;
import clases.Docente;
import frames.AdminLogin;
import frames.SeleccionArea;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.*;
import javax.swing.SwingConstants;

/**
 *
 * @author raulr
 */
public class LoginPrincipal extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginPrincipal
     */
    public LoginPrincipal() {
        initComponents();
         this.setLocationRelativeTo(null);
         
    ImageIcon logo = new ImageIcon("src/imagenes/logo ute feo PEENEGE1111.png");
    Logoutes.setIcon(logo);
    Logoutes.setHorizontalAlignment(SwingConstants.CENTER);    //esto para la imagen

            
btnIniciar.setBackground(new java.awt.Color(37, 137, 126));
btnIniciar.setForeground(java.awt.Color.black);
//estos 2 son pal boton

 jLabel2.setOpaque(true);
 jLabel2.setForeground(Color.black);
 jLabel2.setFont(new Font("Segoe UI", Font.BOLD, 30));
 jLabel2.setHorizontalAlignment(SwingConstants.CENTER);
 jLabel2.setBounds(0, 0, this.getWidth(), 80); // la altura del biblioteca , osea mandarlo hasta arriba del frame
 jLabel2.setHorizontalAlignment(SwingConstants.CENTER); // pa centrar texto
 jLabel2.setOpaque(false); // mostrar fondo
 jLabel2.setBackground(new Color(37, 137, 126)); // verde chido
        
    }
    //Alumno alumno1 = new Alumno();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Logoutes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 230, -1));

        jPanel2.setBackground(new java.awt.Color(29, 136, 120));

        Logoutes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo ute feo PEENEGE1111.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(Logoutes)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Logoutes)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 120));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel3.setText("Matrícula o código");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 220, -1));

        btnIniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar.setText("Ingresar");
        btnIniciar.setBorder(null);
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 170, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setText("Biblioteca escolar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed

        String usuario=txtusuario.getText().trim();
      
        if(usuario.length()==3){
            //Caso para docente
            String codDocente= usuario;
            CLogin login = new CLogin();
            Docente docente1 = login.loginDocente(codDocente);
            if(docente1!= null){
                     //En caso de que se escriba
                        SeleccionAreaDoc area = new SeleccionAreaDoc(docente1);
                        area.setVisible(true);
            this.dispose();
        }                
        }else{
            if(usuario.length()==5){
                //Caso para admin
                //Crea una variable booleana que en caso de que de verdadero, te mandará a
                //validar tus credenciales de administrador
                CLogin resultados = new CLogin();
                boolean acceso = resultados.loginAdmin(usuario);
                if(acceso){
            AdminLogin loginAdmin = new AdminLogin(); //aqui se abrira el frame de veradmin
            loginAdmin.setVisible(true);
            this.dispose();
        }               
            }else{
                    {if(usuario.length()==9){
                    String matricula= usuario;
                    CLogin login = new CLogin();
                    Alumno alumno1= login.loginAlumno(matricula);
                     if(alumno1!= null){
                     //En caso de que se escriba
                        SeleccionArea area = new SeleccionArea(alumno1);
                        area.setVisible(true);
            this.dispose();
        }        
            }else{
                     showMessageDialog(null, "Introduce una matrícula o un código de docente válido");
                    }
          }
        }
      }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logoutes;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
