/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import clases.Docente;
import clases.AreasBiblioteca;
import clases.RegisVisDoc;
import clases.RegistroVisitaAlumno;
import frames.LoginPrincipal;
import static javax.swing.JOptionPane.*;
/**
 *
 * @author raulr
 */
public class SeleccionAreaDoc extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionAreaDoc
     */
    public Docente docente;
    public SeleccionAreaDoc(Docente docente1) {
        initComponents();
         this.setLocationRelativeTo(null);
        this.docente=docente1;     
        System.out.println("La matrícula recibida es: " + docente.getIdDocente());
    }
    
    int idAreaBiblioteca;
    String nombreArea;
    
    
    public SeleccionAreaDoc(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        area5 = new javax.swing.JButton();
        area6 = new javax.swing.JButton();
        area7 = new javax.swing.JButton();
        area8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        logute = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zzz.jpeg"))); // NOI18N
        area5.setText("Area 1");
        area5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area5ActionPerformed(evt);
            }
        });
        jPanel3.add(area5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, 140));

        area6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a3.jpeg"))); // NOI18N
        area6.setText("Area 3");
        area6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area6ActionPerformed(evt);
            }
        });
        jPanel3.add(area6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 250, 140));

        area7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2025-07-31 at 4.39.55 AM (1).jpeg"))); // NOI18N
        area7.setText("Area 2");
        area7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area7ActionPerformed(evt);
            }
        });
        jPanel3.add(area7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 260, 140));

        area8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a4 (2).jpeg"))); // NOI18N
        area8.setText("Area 4");
        area8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area8ActionPerformed(evt);
            }
        });
        jPanel3.add(area8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 260, 140));

        jPanel4.setBackground(new java.awt.Color(39, 139, 128));

        logute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo ute feo PEENEGE1111.png"))); // NOI18N
        logute.setText("jLabel5");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Selecciona tu Area");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logute, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logute, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Centro de computo");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Lobby");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Sala de Idiomas");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Sala de Lectura");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void area5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area5ActionPerformed
        idAreaBiblioteca= 1; nombreArea= "Sala de lectura";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
                                         

    }//GEN-LAST:event_area5ActionPerformed

    private void area6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area6ActionPerformed

         idAreaBiblioteca= 3; nombreArea= "Sala de idiomas";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area6ActionPerformed

    private void area7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area7ActionPerformed
        idAreaBiblioteca= 2; nombreArea= "Centro de cómputo";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area7ActionPerformed

    private void area8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area8ActionPerformed
        idAreaBiblioteca= 4; nombreArea= "Lobby";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionAreaDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton area5;
    private javax.swing.JButton area6;
    private javax.swing.JButton area7;
    private javax.swing.JButton area8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logute;
    // End of variables declaration//GEN-END:variables
}
