/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import clases.Alumno;
import clases.AreasBiblioteca;
import clases.RegistroVisitaAlumno;
import static javax.swing.JOptionPane.*;

/**
 *
 * @author raulr
 */
public class SeleccionArea extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionArea
     */
    public Alumno alumno;
    public SeleccionArea(Alumno alumno1) {
        initComponents();
         this.setLocationRelativeTo(null);
        this.alumno=alumno1;     
        System.out.println("La matrícula recibida es: " + alumno.getIdAlumno());
    }
    
    int idAreaBiblioteca;
    String nombreArea;
    
    
    public SeleccionArea(){
        
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        area1 = new javax.swing.JButton();
        area3 = new javax.swing.JButton();
        area2 = new javax.swing.JButton();
        area4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logute = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/zzz.jpeg"))); // NOI18N
        area1.setText("Area 1");
        area1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1ActionPerformed(evt);
            }
        });
        jPanel1.add(area1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 250, 140));

        area3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a3.jpeg"))); // NOI18N
        area3.setText("Area 3");
        area3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3ActionPerformed(evt);
            }
        });
        jPanel1.add(area3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 250, 140));

        area2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/WhatsApp Image 2025-07-31 at 4.39.55 AM (1).jpeg"))); // NOI18N
        area2.setText("Area 2");
        area2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2ActionPerformed(evt);
            }
        });
        jPanel1.add(area2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 260, 140));

        area4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a4 (2).jpeg"))); // NOI18N
        area4.setText("Area 4");
        area4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area4ActionPerformed(evt);
            }
        });
        jPanel1.add(area4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 260, 140));

        jPanel2.setBackground(new java.awt.Color(39, 139, 128));

        logute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo ute feo PEENEGE1111.png"))); // NOI18N
        logute.setText("jLabel5");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("Selecciona tu Area");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(logute, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(343, 343, 343))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logute, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Centro de computo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Lobby");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Sala de Idiomas");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Sala de Lectura");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void area3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3ActionPerformed
        idAreaBiblioteca= 3; nombreArea= "Sala de idiomas";
        int idAlumno= alumno.getIdAlumno();
        
        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegistroVisitaAlumno regAl = new RegistroVisitaAlumno();
        regAl.registrarVisita(idAlumno, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + alumno.getNombres());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area3ActionPerformed

    private void area1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1ActionPerformed
       idAreaBiblioteca= 1; nombreArea= "Sala de lectura";
        int idAlumno= alumno.getIdAlumno();
        
        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegistroVisitaAlumno regAl = new RegistroVisitaAlumno();
        regAl.registrarVisita(idAlumno, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + alumno.getNombres());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area1ActionPerformed

    private void area2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2ActionPerformed
       idAreaBiblioteca= 2; nombreArea= "Centro de cómputo";
        int idAlumno= alumno.getIdAlumno();
        
        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegistroVisitaAlumno regAl = new RegistroVisitaAlumno();
        regAl.registrarVisita(idAlumno, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + alumno.getNombres());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area2ActionPerformed

    private void area4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area4ActionPerformed
        idAreaBiblioteca= 4; nombreArea= "Lobby";
        int idAlumno= alumno.getIdAlumno();
        
        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegistroVisitaAlumno regAl = new RegistroVisitaAlumno();
        regAl.registrarVisita(idAlumno, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + alumno.getNombres());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionArea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton area1;
    private javax.swing.JButton area2;
    private javax.swing.JButton area3;
    private javax.swing.JButton area4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logute;
    // End of variables declaration//GEN-END:variables
}
