/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;
import clases.Docente;
import clases.AreasBiblioteca;
import clases.RegisVisDoc;
import clases.RegistroVisitaAlumno;
import static javax.swing.JOptionPane.*;
/**
 *
 * @author raulr
 */
public class SeleccionAreaDoc extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionAreaDoc
     */
    public Docente docente;
    public SeleccionAreaDoc(Docente docente1) {
        initComponents();
         this.setLocationRelativeTo(null);
        this.docente=docente1;     
        System.out.println("La matrícula recibida es: " + docente.getIdDocente());
    }
    
    int idAreaBiblioteca;
    String nombreArea;
    
    
    public SeleccionAreaDoc(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        area1 = new javax.swing.JButton();
        area3 = new javax.swing.JButton();
        area2 = new javax.swing.JButton();
        area4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        area1.setText("Area 1");
        area1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area1ActionPerformed(evt);
            }
        });
        jPanel1.add(area1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 75, -1));

        area3.setText("Area 3");
        area3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area3ActionPerformed(evt);
            }
        });
        jPanel1.add(area3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 75, -1));

        area2.setText("Area 2");
        area2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area2ActionPerformed(evt);
            }
        });
        jPanel1.add(area2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 75, -1));

        area4.setText("Area 4");
        area4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                area4ActionPerformed(evt);
            }
        });
        jPanel1.add(area4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 75, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 84, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 528, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void area1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area1ActionPerformed
        idAreaBiblioteca= 1; nombreArea= "Sala de lectura";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area1ActionPerformed

    private void area3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area3ActionPerformed
        idAreaBiblioteca= 3; nombreArea= "Sala de idiomas";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area3ActionPerformed

    private void area2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area2ActionPerformed
        idAreaBiblioteca= 2; nombreArea= "Centro de cómputo";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area2ActionPerformed

    private void area4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_area4ActionPerformed
        idAreaBiblioteca= 4; nombreArea= "Lobby";
        int idDocente= docente.getIdDocente();

        AreasBiblioteca area = new AreasBiblioteca(idAreaBiblioteca, nombreArea);
        RegisVisDoc regDoc = new RegisVisDoc();
        regDoc.registrarVisita(idDocente, idAreaBiblioteca);
        showMessageDialog(null, "Bienvenido " + docente.getNombre());
        LoginPrincipal lp = new LoginPrincipal();
        lp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_area4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionAreaDoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionAreaDoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton area1;
    private javax.swing.JButton area2;
    private javax.swing.JButton area3;
    private javax.swing.JButton area4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
