/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import clases.Carrera;
import clases.Conexion;
import clases.Grupo;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author angel
 */
public class VerGrupo extends javax.swing.JFrame {
    public JPopupMenu menu;

    /**
     * Creates new form VerGrupo
     */
    public VerGrupo() {
        initComponents();
        mostrarGrupo();
    }
    public void mostrarGrupo(){
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Grupo");
                modelo.addColumn("Carrera");
    try{
           Conexion conexion = new Conexion();
           Connection con = conexion.con; 
                String sql ="SELECT g.idGrupo, g.nombreGrupo, g.idCarrera, c.carreraNombre AS carreraNombre FROM grupo g INNER JOIN carrera c ON g.idCarrera = c.idCarrera";
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet datos = ps.executeQuery();
                
                ArrayList<Grupo> VerGrupo = new ArrayList<>();
                while(datos.next()){
            int idGrupo = datos.getInt("idGrupo");
            String nombreGrupo = datos.getString("nombreGrupo");
            int idCarrera = datos.getInt("idCarrera");
            String nombreCarrera = datos.getString("carreraNombre");
            
            Grupo grupo = new Grupo(idGrupo,nombreGrupo);
            Carrera carrera = new Carrera(idCarrera,nombreCarrera);
            modelo.addRow(new Object[]{
               
             grupo.getNombreGrupo(),
                carrera.getnombreCarrera(),
                
              
            
             });
             VerGrupo.add(grupo);
}
               tabla_grupo.setModel(modelo); 
         menu = new JPopupMenu();
         JMenuItem itemEditar = new JMenuItem("Editar");
         JMenuItem itemEliminar = new JMenuItem("Eliminar");
         menu.add(itemEditar);
         menu.add(itemEliminar);

         tabla_grupo.addMouseListener(new java.awt.event.MouseAdapter(){
             public void mousePressed(java.awt.event.MouseEvent evt){
                 if (evt.isPopupTrigger()|| evt.getButton() == java.awt.event.MouseEvent.BUTTON3){
                     int fila = tabla_grupo.rowAtPoint(evt.getPoint());
                 {
                             if (fila >= 0){
                                tabla_grupo.setRowSelectionInterval(fila, fila);
                                menu.show(tabla_grupo, evt.getX(), evt.getY());
                             }
         }
         }}
                 public void mouseReleased(java.awt.event.MouseEvent evt){
                 mousePressed(evt);
                 }});
         itemEditar.addActionListener(e -> {
                 int fila = tabla_grupo.getSelectedRow();
                 if (fila >=0){
                       Grupo g = VerGrupo.get(fila);
                    new EditarGrupo(g).setVisible(true);
                    
                 }
});
        itemEliminar.addActionListener(e ->{
           int fila = tabla_grupo.getSelectedRow(); 
           if (fila >=0){
               Grupo g = VerGrupo.get(fila);
               int repuesta = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar al grupo", "si", JOptionPane.YES_OPTION);
               if (repuesta == JOptionPane.YES_OPTION){
                   try{
                       PreparedStatement ps2 = con.prepareStatement("DELETE FROM grupo WHERE idGrupo=? ");
                       ps2.setInt(1, g.getIdGrupo());
                       ps2.executeUpdate();
                       mostrarGrupo();
                   }catch(Exception e2){
                       JOptionPane.showMessageDialog(null,"Error al guardar"+e2.getMessage());
                   }
               }
           }
        });
    }
    catch(Exception e){
            showMessageDialog(null, "Error al cargar la base de datos" + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_grupo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(29, 136, 120));
        jButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 393, -1, -1));

        jPanel2.setBackground(new java.awt.Color(29, 136, 120));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setText("Bibioteca");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 0, 219, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 719, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Lista de los grupos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 88, 210, -1));

        tabla_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Grupo", "Carrera"
            }
        ));
        jScrollPane1.setViewportView(tabla_grupo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 680, 202));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //instanciamos la clase de la lista
        CrearGrupo g = new CrearGrupo();
        //indicamos que esa lista sea visible
        g.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_grupo;
    // End of variables declaration//GEN-END:variables
}
